name: emacs-tealeg
version: snapshot
summary: GNU Emacs Snapshot
description: An extensible, customizable, free/libre text editor -- and more.
confinement: strict

apps:
  emacs-tealeg:
    command: emacs-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
      - network-bind
  emacsclient-tealeg:
    command: emacsclient-tealeg
    plugs:
      - home
      - x11
      - unity7
      - gsettings
      - network
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags

parts:
  emacs-tealeg:
    plugin: copy
    files:
      emacs-tealeg.sh: bin/emacs-tealeg
      emacsclient-tealeg.sh: bin/emacsclient-tealeg
  emacs:
    plugin: autotools
    source: git://git.sv.gnu.org/emacs.git
    source-type: git
    install-via: prefix
    build-packages:
      - libgnutls-dev
      - libgif-dev
      - libxpm-dev
      - libjpeg-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgnutls30
      - libgif7
      - libxpm4
      - libjpeg8
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop/gtk3
