name: emacs
version: 25.1
summary: GNU Emacs 25.1
description: An extensible, customizable, free/libre text editor -- and more.
confinement: strict

apps:
  emacs:
    command: desktop-launch emacs
    plugs:
      - home
      - x11
      - gsettings
      - network
      - network-bind
  ctags:
    command: ctags
  ebrowse:
    command: ebrowse
  etags:
    command: etags

parts:
  desktop/gtk3:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - dmz-cursor-theme
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - libappindicator3-1
      - locales-all
    prime:
      - -usr/lib/*/libmir*
      - -usr/share/doc/libmir*
  emacs:
    plugin: autotools
    source: https://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.gz
    source-type: tar
    install-via: prefix
    configflags:
      - CFLAGS=-no-pie
      - --without-makeinfo
    build-packages:
      - libgnutls28-dev
      - libgif-dev
      - libxpm-dev
      - libjpeg62-turbo-dev
      - libtiff5-dev
      - libncursesw5-dev
      - libsm-dev
      - libxft-dev
    stage-packages:
      - libgnutls30
      - libgif7
      - libxpm4
      - libjpeg62-turbo
      - libtiff5
      - libncursesw5
      - libsm6
      - libxft2
    after:
      - desktop/gtk3
